// Wails runtime bridge
// This file is auto-generated by wails but we provide a typed version
// The actual runtime is injected by Wails at build time

// @ts-ignore
export const GetDevices = () => window['go']['main']['App']['GetDevices']()
// @ts-ignore
export const GetDeviceInfo = () => window['go']['main']['App']['GetDeviceInfo']()
// @ts-ignore
export const GetSecurityOverview = () => window['go']['main']['App']['GetSecurityOverview']()
// @ts-ignore
export const GetDeviceMode = () => window['go']['main']['App']['GetDeviceMode']()
// @ts-ignore
export const Reboot = (mode: string) => window['go']['main']['App']['Reboot'](mode)
// @ts-ignore
export const GetBinaryInfo = () => window['go']['main']['App']['GetBinaryInfo']()
// @ts-ignore
export const CheckSystemRequirements = () => window['go']['main']['App']['CheckSystemRequirements']()
// @ts-ignore
export const ShowWindow = () => window['go']['main']['App']['ShowWindow']()
// @ts-ignore
export const HideWindow = () => window['go']['main']['App']['HideWindow']()
// @ts-ignore
export const QuitApp = () => window['go']['main']['App']['QuitApp']()
// @ts-ignore
export const TrayAvailable = () => window['go']['main']['App']['TrayAvailable']()
// @ts-ignore
export const OpenURL = (url: string) => window['go']['main']['App']['OpenURL'](url)
// @ts-ignore
export const SetAdbPath = (path: string) => window['go']['main']['App']['SetAdbPath'](path)
// @ts-ignore
export const SetFastbootPath = (path: string) => window['go']['main']['App']['SetFastbootPath'](path)
// @ts-ignore
export const CancelOperation = () => window['go']['main']['App']['CancelOperation']()

// File ops
// @ts-ignore
export const ListFiles = (path: string) => window['go']['main']['App']['ListFiles'](path)
// @ts-ignore
export const PushFile = (local: string, remote: string) => window['go']['main']['App']['PushFile'](local, remote)
// @ts-ignore
export const PullFile = (remote: string, local: string) => window['go']['main']['App']['PullFile'](remote, local)
// @ts-ignore
export const CreateFolder = (path: string) => window['go']['main']['App']['CreateFolder'](path)
// @ts-ignore
export const DeleteFile = (path: string) => window['go']['main']['App']['DeleteFile'](path)
// @ts-ignore
export const DeleteMultipleFiles = (paths: string[]) => window['go']['main']['App']['DeleteMultipleFiles'](paths)
// @ts-ignore
export const RenameFile = (oldPath: string, newPath: string) => window['go']['main']['App']['RenameFile'](oldPath, newPath)
// @ts-ignore
export const CopyFile = (src: string, dst: string) => window['go']['main']['App']['CopyFile'](src, dst)
// @ts-ignore
export const PullMultipleFiles = (paths: string[]) => window['go']['main']['App']['PullMultipleFiles'](paths)
// @ts-ignore
export const SelectFileForPush = () => window['go']['main']['App']['SelectFileForPush']()
// @ts-ignore
export const PushWithProgress = (local: string, remoteDir: string) => window['go']['main']['App']['PushWithProgress'](local, remoteDir)
// @ts-ignore
export const PullPathsWithProgress = (paths: string[]) => window['go']['main']['App']['PullPathsWithProgress'](paths)
// @ts-ignore
export const SaveTextFile = (defaultName: string, content: string) => window['go']['main']['App']['SaveTextFile'](defaultName, content)
// @ts-ignore
export const HomeDir = () => window['go']['main']['App']['HomeDir']()
// @ts-ignore
export const ListLocalFiles = (path: string) => window['go']['main']['App']['ListLocalFiles'](path)
// @ts-ignore
export const PushPathsWithProgress = (localPaths: string[], remoteDir: string) => window['go']['main']['App']['PushPathsWithProgress'](localPaths, remoteDir)

// Screen mirror (scrcpy)
// @ts-ignore
export const ScrcpyAvailable = () => window['go']['main']['App']['ScrcpyAvailable']()
// @ts-ignore
export const ScrcpyRunning = () => window['go']['main']['App']['ScrcpyRunning']()
// @ts-ignore
export const StartScrcpy = (opts: any) => window['go']['main']['App']['StartScrcpy'](opts)
// @ts-ignore
export const StopScrcpy = () => window['go']['main']['App']['StopScrcpy']()
// @ts-ignore
export const CaptureScreenshot = () => window['go']['main']['App']['CaptureScreenshot']()

// Package ops
// @ts-ignore
export const ListPackages = (filter: string) => window['go']['main']['App']['ListPackages'](filter)
// @ts-ignore
export const InstallPackage = (path: string) => window['go']['main']['App']['InstallPackage'](path)
// @ts-ignore
export const UninstallPackage = (pkg: string) => window['go']['main']['App']['UninstallPackage'](pkg)
// @ts-ignore
export const DisablePackage = (pkg: string) => window['go']['main']['App']['DisablePackage'](pkg)
// @ts-ignore
export const EnablePackage = (pkg: string) => window['go']['main']['App']['EnablePackage'](pkg)
// @ts-ignore
export const ClearData = (pkg: string) => window['go']['main']['App']['ClearData'](pkg)
// @ts-ignore
export const PullApk = (pkg: string) => window['go']['main']['App']['PullApk'](pkg)
// @ts-ignore
export const ForceStopPackage = (pkg: string) => window['go']['main']['App']['ForceStopPackage'](pkg)
// @ts-ignore
export const GetPackageInfo = (pkg: string) => window['go']['main']['App']['GetPackageInfo'](pkg)
// @ts-ignore
export const UninstallMultiplePackages = (pkgs: string[]) => window['go']['main']['App']['UninstallMultiplePackages'](pkgs)
// @ts-ignore
export const DisableMultiplePackages = (pkgs: string[]) => window['go']['main']['App']['DisableMultiplePackages'](pkgs)
// @ts-ignore
export const UninstallAndDisableMultiplePackages = (pkgs: string[]) => window['go']['main']['App']['UninstallAndDisableMultiplePackages'](pkgs)
// @ts-ignore
export const EnableMultiplePackages = (pkgs: string[]) => window['go']['main']['App']['EnableMultiplePackages'](pkgs)
// @ts-ignore
export const RestoreMultiplePackages = (pkgs: string[]) => window['go']['main']['App']['RestoreMultiplePackages'](pkgs)
// @ts-ignore
export const RestorePackage = (pkg: string) => window['go']['main']['App']['RestorePackage'](pkg)
// @ts-ignore
export const SelectFileForInstall = () => window['go']['main']['App']['SelectFileForInstall']()
// @ts-ignore
export const SideloadPackage = (path: string) => window['go']['main']['App']['SideloadPackage'](path)
// @ts-ignore
export const SelectApkFolder = () => window['go']['main']['App']['SelectApkFolder']()
// @ts-ignore
export const SelectMultipleApkFiles = () => window['go']['main']['App']['SelectMultipleApkFiles']()
// @ts-ignore
export const ListApksInFolder = (folder: string) => window['go']['main']['App']['ListApksInFolder'](folder)
// @ts-ignore
export const StatApkFiles = (paths: string[]) => window['go']['main']['App']['StatApkFiles'](paths)
// @ts-ignore
export const InstallApksWithProgress = (paths: string[]) => window['go']['main']['App']['InstallApksWithProgress'](paths)

// Shell
// @ts-ignore
export const RunShellCommand = (cmd: string) => window['go']['main']['App']['RunShellCommand'](cmd)
// @ts-ignore
export const RunAdbHostCommand = (args: string) => window['go']['main']['App']['RunAdbHostCommand'](args)

// Wireless
// @ts-ignore
export const EnableWirelessAdb = (port: string) => window['go']['main']['App']['EnableWirelessAdb'](port)
// @ts-ignore
export const ConnectWirelessAdb = (ip: string, port: string) => window['go']['main']['App']['ConnectWirelessAdb'](ip, port)
// @ts-ignore
export const DisconnectWirelessAdb = (ip: string, port: string) => window['go']['main']['App']['DisconnectWirelessAdb'](ip, port)

// Fastboot
// @ts-ignore
export const GetFastbootDevices = () => window['go']['main']['App']['GetFastbootDevices']()
// @ts-ignore
export const FlashPartition = (partition: string, file: string, force: boolean) => window['go']['main']['App']['FlashPartition'](partition, file, force)
// @ts-ignore
export const FastbootGetVar = (variable: string) => window['go']['main']['App']['FastbootGetVar'](variable)
// @ts-ignore
export const SelectFileForFlash = () => window['go']['main']['App']['SelectFileForFlash']()
// @ts-ignore
export const FastbootBoot = (file: string) => window['go']['main']['App']['FastbootBoot'](file)
// @ts-ignore
export const FlashBootImage = (partition: string, file: string, slot: string, force: boolean) => window['go']['main']['App']['FlashBootImage'](partition, file, slot, force)
// @ts-ignore
export const FastbootFlashing = (action: string) => window['go']['main']['App']['FastbootFlashing'](action)
// @ts-ignore
export const FastbootReboot = (target: string) => window['go']['main']['App']['FastbootReboot'](target)
// @ts-ignore
export const FlasherDeviceInfo = () => window['go']['main']['App']['FlasherDeviceInfo']()
// Magisk root tools
// @ts-ignore
export const MagiskInstalled = () => window['go']['main']['App']['MagiskInstalled']()
// @ts-ignore
export const InstallMagisk = () => window['go']['main']['App']['InstallMagisk']()
// @ts-ignore
export const ExtractBootImages = (zipPath: string) => window['go']['main']['App']['ExtractBootImages'](zipPath)
// @ts-ignore
export const PushImageToDevice = (localPath: string) => window['go']['main']['App']['PushImageToDevice'](localPath)
// @ts-ignore
export const OpenMagisk = () => window['go']['main']['App']['OpenMagisk']()
// @ts-ignore
export const PullPatchedBoot = () => window['go']['main']['App']['PullPatchedBoot']()
// @ts-ignore
export const ListMagiskModules = () => window['go']['main']['App']['ListMagiskModules']()
// @ts-ignore
export const ToggleMagiskModule = (id: string, enable: boolean) => window['go']['main']['App']['ToggleMagiskModule'](id, enable)
// @ts-ignore
export const RemoveMagiskModule = (id: string) => window['go']['main']['App']['RemoveMagiskModule'](id)
// Firmware download
// @ts-ignore
export const ListFirmware = (codename: string, kind: string) => window['go']['main']['App']['ListFirmware'](codename, kind)
// @ts-ignore
export const DownloadFirmware = (url: string, sha256: string) => window['go']['main']['App']['DownloadFirmware'](url, sha256)
// @ts-ignore
export const ListPayloadPartitions = (zipPath: string) => window['go']['main']['App']['ListPayloadPartitions'](zipPath)
// @ts-ignore
export const ExtractPayloadPartition = (zipPath: string, name: string) => window['go']['main']['App']['ExtractPayloadPartition'](zipPath, name)
// @ts-ignore
export const AnalyzeBootImage = (path: string) => window['go']['main']['App']['AnalyzeBootImage'](path)
// @ts-ignore
export const HashFile = (path: string) => window['go']['main']['App']['HashFile'](path)
// @ts-ignore
export const SelectAnyFile = () => window['go']['main']['App']['SelectAnyFile']()

// Logcat
// @ts-ignore
export const StartLogcat = (filter: string, buffer: string) => window['go']['main']['App']['StartLogcat'](filter, buffer)
// @ts-ignore
export const StopLogcat = () => window['go']['main']['App']['StopLogcat']()
// @ts-ignore
export const ClearLogcat = () => window['go']['main']['App']['ClearLogcat']()
// @ts-ignore
export const LogcatProcessNames = (): Promise<Record<string, string>> => window['go']['main']['App']['LogcatProcessNames']()

// App inspection
// @ts-ignore
export const InspectApp = (pkg: string) => window['go']['main']['App']['InspectApp'](pkg)
// @ts-ignore
export const ScanAppPrivacy = (pkg: string) => window['go']['main']['App']['ScanAppPrivacy'](pkg)
// @ts-ignore
export const ListActivities = (pkg: string) => window['go']['main']['App']['ListActivities'](pkg)
// @ts-ignore
export const StartActivity = (component: string) => window['go']['main']['App']['StartActivity'](component)
// @ts-ignore
export const StartIntentAction = (action: string, data: string) => window['go']['main']['App']['StartIntentAction'](action, data)
// GSI Loader
// @ts-ignore
export const GsiCompat = () => window['go']['main']['App']['GsiCompat']()
// @ts-ignore
export const GsiDsuStatus = () => window['go']['main']['App']['GsiDsuStatus']()
// @ts-ignore
export const InstallDsu = (imagePath: string, systemSize: number, userdataSize: number) => window['go']['main']['App']['InstallDsu'](imagePath, systemSize, userdataSize)
// @ts-ignore
export const DsuEnable = () => window['go']['main']['App']['DsuEnable']()
// @ts-ignore
export const DsuDisable = () => window['go']['main']['App']['DsuDisable']()
// @ts-ignore
export const DsuWipe = () => window['go']['main']['App']['DsuWipe']()
// @ts-ignore
export const FlashGsiSystem = (imagePath: string, opts: any) => window['go']['main']['App']['FlashGsiSystem'](imagePath, opts)
// @ts-ignore
export const CheckPinning = (pkg: string) => window['go']['main']['App']['CheckPinning'](pkg)

// Certificates
// @ts-ignore
export const ListSystemCerts = () => window['go']['main']['App']['ListSystemCerts']()
// @ts-ignore
export const ListUserCerts = () => window['go']['main']['App']['ListUserCerts']()
// @ts-ignore
export const InstallUserCert = (path: string) => window['go']['main']['App']['InstallUserCert'](path)
// @ts-ignore
export const RemoveUserCert = (filename: string) => window['go']['main']['App']['RemoveUserCert'](filename)
// @ts-ignore
export const SelectCertFile = () => window['go']['main']['App']['SelectCertFile']()

// Backup
// @ts-ignore
export const StartBackup = (opts: any, path: string) => window['go']['main']['App']['StartBackup'](opts, path)
// @ts-ignore
export const RestoreBackup = (path: string) => window['go']['main']['App']['RestoreBackup'](path)
// @ts-ignore
export const SelectBackupFile = () => window['go']['main']['App']['SelectBackupFile']()
// @ts-ignore
export const BackupSingleApp = (pkg: string, apk: boolean) => window['go']['main']['App']['BackupSingleApp'](pkg, apk)

// Props
// @ts-ignore
export const GetAllProps = () => window['go']['main']['App']['GetAllProps']()
// @ts-ignore
export const SetProp = (key: string, value: string) => window['go']['main']['App']['SetProp'](key, value)
// @ts-ignore
export const GetProp = (key: string) => window['go']['main']['App']['GetProp'](key)

// APK Auditor
// @ts-ignore
export const SelectAPKForAudit = () => window['go']['main']['App']['SelectAPKForAudit']()
// @ts-ignore
export const AuditAPK = (path: string) => window['go']['main']['App']['AuditAPK'](path)
// @ts-ignore
export const AuditInstalledApp = (pkg: string) => window['go']['main']['App']['AuditInstalledApp'](pkg)
// @ts-ignore
export const ReadAPKEntry = (apkPath: string, entry: string) => window['go']['main']['App']['ReadAPKEntry'](apkPath, entry)
// @ts-ignore
export const ExportAudit = (audit: any, format: string) => window['go']['main']['App']['ExportAudit'](audit, format)

// App lock
// @ts-ignore
export const AppLockStatus = (): Promise<{ enabled: boolean; requireForDanger: boolean }> => window['go']['main']['App']['AppLockStatus']()
// @ts-ignore
export const VerifyAppPassword = (password: string): Promise<boolean> => window['go']['main']['App']['VerifyAppPassword'](password)
// @ts-ignore
export const SetAppPassword = (current: string, next: string): Promise<void> => window['go']['main']['App']['SetAppPassword'](current, next)
// @ts-ignore
export const DisableAppLock = (current: string): Promise<void> => window['go']['main']['App']['DisableAppLock'](current)
// @ts-ignore
export const SetRequireForDanger = (current: string, require: boolean): Promise<void> => window['go']['main']['App']['SetRequireForDanger'](current, require)
// @ts-ignore
export const UnlockDanger = (password: string): Promise<boolean> => window['go']['main']['App']['UnlockDanger'](password)
