// Wails runtime bridge
// This file is auto-generated by wails but we provide a typed version
// The actual runtime is injected by Wails at build time

// @ts-ignore
export const GetDevices = () => window['go']['main']['App']['GetDevices']()
// @ts-ignore
export const GetDeviceInfo = () => window['go']['main']['App']['GetDeviceInfo']()
// @ts-ignore
export const GetDeviceMode = () => window['go']['main']['App']['GetDeviceMode']()
// @ts-ignore
export const Reboot = (mode: string) => window['go']['main']['App']['Reboot'](mode)
// @ts-ignore
export const GetBinaryInfo = () => window['go']['main']['App']['GetBinaryInfo']()
// @ts-ignore
export const CheckSystemRequirements = () => window['go']['main']['App']['CheckSystemRequirements']()
// @ts-ignore
export const SetAdbPath = (path: string) => window['go']['main']['App']['SetAdbPath'](path)
// @ts-ignore
export const SetFastbootPath = (path: string) => window['go']['main']['App']['SetFastbootPath'](path)
// @ts-ignore
export const CancelOperation = () => window['go']['main']['App']['CancelOperation']()

// File ops
// @ts-ignore
export const ListFiles = (path: string) => window['go']['main']['App']['ListFiles'](path)
// @ts-ignore
export const PushFile = (local: string, remote: string) => window['go']['main']['App']['PushFile'](local, remote)
// @ts-ignore
export const PullFile = (remote: string, local: string) => window['go']['main']['App']['PullFile'](remote, local)
// @ts-ignore
export const CreateFolder = (path: string) => window['go']['main']['App']['CreateFolder'](path)
// @ts-ignore
export const DeleteFile = (path: string) => window['go']['main']['App']['DeleteFile'](path)
// @ts-ignore
export const DeleteMultipleFiles = (paths: string[]) => window['go']['main']['App']['DeleteMultipleFiles'](paths)
// @ts-ignore
export const RenameFile = (oldPath: string, newPath: string) => window['go']['main']['App']['RenameFile'](oldPath, newPath)
// @ts-ignore
export const CopyFile = (src: string, dst: string) => window['go']['main']['App']['CopyFile'](src, dst)
// @ts-ignore
export const PullMultipleFiles = (paths: string[]) => window['go']['main']['App']['PullMultipleFiles'](paths)
// @ts-ignore
export const SelectFileForPush = () => window['go']['main']['App']['SelectFileForPush']()

// Package ops
// @ts-ignore
export const ListPackages = (filter: string) => window['go']['main']['App']['ListPackages'](filter)
// @ts-ignore
export const InstallPackage = (path: string) => window['go']['main']['App']['InstallPackage'](path)
// @ts-ignore
export const UninstallPackage = (pkg: string) => window['go']['main']['App']['UninstallPackage'](pkg)
// @ts-ignore
export const DisablePackage = (pkg: string) => window['go']['main']['App']['DisablePackage'](pkg)
// @ts-ignore
export const EnablePackage = (pkg: string) => window['go']['main']['App']['EnablePackage'](pkg)
// @ts-ignore
export const ClearData = (pkg: string) => window['go']['main']['App']['ClearData'](pkg)
// @ts-ignore
export const PullApk = (pkg: string) => window['go']['main']['App']['PullApk'](pkg)
// @ts-ignore
export const ForceStopPackage = (pkg: string) => window['go']['main']['App']['ForceStopPackage'](pkg)
// @ts-ignore
export const GetPackageInfo = (pkg: string) => window['go']['main']['App']['GetPackageInfo'](pkg)
// @ts-ignore
export const UninstallMultiplePackages = (pkgs: string[]) => window['go']['main']['App']['UninstallMultiplePackages'](pkgs)
// @ts-ignore
export const DisableMultiplePackages = (pkgs: string[]) => window['go']['main']['App']['DisableMultiplePackages'](pkgs)
// @ts-ignore
export const EnableMultiplePackages = (pkgs: string[]) => window['go']['main']['App']['EnableMultiplePackages'](pkgs)
// @ts-ignore
export const SelectFileForInstall = () => window['go']['main']['App']['SelectFileForInstall']()
// @ts-ignore
export const SideloadPackage = (path: string) => window['go']['main']['App']['SideloadPackage'](path)

// Shell
// @ts-ignore
export const RunShellCommand = (cmd: string) => window['go']['main']['App']['RunShellCommand'](cmd)
// @ts-ignore
export const RunAdbHostCommand = (args: string) => window['go']['main']['App']['RunAdbHostCommand'](args)

// Wireless
// @ts-ignore
export const EnableWirelessAdb = (port: string) => window['go']['main']['App']['EnableWirelessAdb'](port)
// @ts-ignore
export const ConnectWirelessAdb = (ip: string, port: string) => window['go']['main']['App']['ConnectWirelessAdb'](ip, port)
// @ts-ignore
export const DisconnectWirelessAdb = (ip: string, port: string) => window['go']['main']['App']['DisconnectWirelessAdb'](ip, port)

// Fastboot
// @ts-ignore
export const GetFastbootDevices = () => window['go']['main']['App']['GetFastbootDevices']()
// @ts-ignore
export const FlashPartition = (partition: string, file: string) => window['go']['main']['App']['FlashPartition'](partition, file)
// @ts-ignore
export const FastbootGetVar = (variable: string) => window['go']['main']['App']['FastbootGetVar'](variable)
// @ts-ignore
export const SelectFileForFlash = () => window['go']['main']['App']['SelectFileForFlash']()

// Logcat
// @ts-ignore
export const StartLogcat = (filter: string, buffer: string) => window['go']['main']['App']['StartLogcat'](filter, buffer)
// @ts-ignore
export const StopLogcat = () => window['go']['main']['App']['StopLogcat']()
// @ts-ignore
export const ClearLogcat = () => window['go']['main']['App']['ClearLogcat']()

// App inspection
// @ts-ignore
export const InspectApp = (pkg: string) => window['go']['main']['App']['InspectApp'](pkg)
// @ts-ignore
export const CheckPinning = (pkg: string) => window['go']['main']['App']['CheckPinning'](pkg)

// Certificates
// @ts-ignore
export const ListSystemCerts = () => window['go']['main']['App']['ListSystemCerts']()
// @ts-ignore
export const ListUserCerts = () => window['go']['main']['App']['ListUserCerts']()
// @ts-ignore
export const InstallUserCert = (path: string) => window['go']['main']['App']['InstallUserCert'](path)
// @ts-ignore
export const RemoveUserCert = (filename: string) => window['go']['main']['App']['RemoveUserCert'](filename)
// @ts-ignore
export const SelectCertFile = () => window['go']['main']['App']['SelectCertFile']()

// Backup
// @ts-ignore
export const StartBackup = (opts: any, path: string) => window['go']['main']['App']['StartBackup'](opts, path)
// @ts-ignore
export const RestoreBackup = (path: string) => window['go']['main']['App']['RestoreBackup'](path)
// @ts-ignore
export const SelectBackupFile = () => window['go']['main']['App']['SelectBackupFile']()
// @ts-ignore
export const BackupSingleApp = (pkg: string, apk: boolean) => window['go']['main']['App']['BackupSingleApp'](pkg, apk)

// Props
// @ts-ignore
export const GetAllProps = () => window['go']['main']['App']['GetAllProps']()
// @ts-ignore
export const SetProp = (key: string, value: string) => window['go']['main']['App']['SetProp'](key, value)
// @ts-ignore
export const GetProp = (key: string) => window['go']['main']['App']['GetProp'](key)
